"""One-shot: convert the Still I Rise analysis JSON into a Remotion TimingContract module."""
import json
from pathlib import Path

ROOT = Path(r"D:\Backup of Important Data for Windows 11 Upgrade\Native Media AI Studio")
src = json.loads((ROOT / "output" / "test-Nathaniel_Smalley___Still_I_Rise-analysis.json").read_text(encoding="utf-8-sig"))

bpm = src["tempo_bpm"]
duration = round(src["duration_seconds"], 2)
beats = src["beat_times"]
sections = src["sections"]
curve = src["energy_curve"]

def beats_ts():
    """Emit BeatEvent literals.

    The analysis only provides onset *times* (no drum classification), so:
    - drumType heuristics: alternating kick/hat at the ~0.615s beat grid
      (97.5 BPM) — enough to drive kick-synced visuals without pretending
      real drum separation exists.
    - energy: onset-strength proxy = gap since previous beat relative to the
      median beat gap, clamped 0.35..1.0.
    """
    out = []
    gaps = [beats[i] - beats[i - 1] if i else 0.615 for i in range(len(beats))]
    med = sorted(gaps)[len(gaps) // 2] or 0.615
    for i, b in enumerate(beats):
        gap = gaps[i]
        drum = "kick" if i % 2 == 0 else "hat"
        strength = min(1.0, max(0.35, gap / med))
        out.append(
            f'    {{ time: {round(b, 3)}, drumType: "{drum}" as DrumType, '
            f'energy: {round(strength, 2)}, isDownbeat: {"true" if i % 4 == 0 else "false"} }}'
        )
    return ",\n".join(out)


def sections_ts():
    """Emit SectionEvent literals, closing gaps so lookups never return null.

    The analyzer emits adjacent-but-gapped sections (204.58 -> 204.86); a null
    section window would drop palettes/energy to fallbacks, so extend each
    section's end to the next section's start (the last keeps its own end).
    """
    out = []
    for i, s in enumerate(sections):
        start = s["start"]
        end = s["end"]
        if i + 1 < len(sections):
            end = max(end, sections[i + 1]["start"])
        out.append(
            f'    {{ type: "{s["type"]}" as SectionType, start: {round(start, 2)}, '
            f"end: {round(end, 2)}, energy: {round(s['energy'], 2)} }}"
        )
    return ",\n".join(out)

def curve_pts():
    n = len(curve)
    dur = src["duration_seconds"]
    out = []
    for i, v in enumerate(curve):
        t = round(i * dur / (n - 1), 2)
        out.append(f"{{ time: {t}, value: {round(v, 3)} }}")
    return ", ".join(out)

def envelope():
    return ", ".join(str(round(v, 3)) for v in curve)

body = f'''/**
 * Still I Rise — TimingContract generated from the real backend analysis.
 *
 * Source: output/test-Nathaniel_Smalley___Still_I_Rise-analysis.json (job 64ab7938)
 * Generated by tools/scripts/generate_still_irise_timing.py — DO NOT hand-edit timings.
 *
 * - {len(beats)} beats @ {bpm} BPM (librosa beat tracking)
 * - {len(sections)} sections (librosa segmentation, energies 0.2-0.9)
 * - {len(curve)}-point energy curve (non-uniform, time-stamped support points)
 */

import type {{ TimingContract, SectionType, DrumType }} from "./timing";

export const STILL_I_RISE_BPM = {bpm};
export const STILL_I_RISE_DURATION_SECONDS = {duration};

export const STILL_I_RISE_TIMING: TimingContract = {{
  filename: "still-i-rise.mp3",
  duration: {duration},
  bpm: {bpm},
  bpmConfidence: {round(src["confidence"], 2)},
  beats: [
{beats_ts()},
  ],
  sections: [
{sections_ts()},
  ],
  energyCurve: [
    {curve_pts()},
  ],
  amplitudeEnvelope: [{envelope()}],
}};
'''

out_dir = ROOT / "packages" / "video-editor" / "src" / "lib"
out_dir.mkdir(parents=True, exist_ok=True)
(out_dir / "stillIRiseTiming.ts").write_text(body, encoding="utf-8")
print(f"Wrote {out_dir / 'stillIRiseTiming.ts'}: {len(beats)} beats, {len(sections)} sections, {len(curve)} curve pts, duration {duration}s @ {bpm} BPM")