/**
 * Track Manager — Table view for pairing prompts and lyrics to tracks.
 */

import { useState, useCallback, useEffect } from "react";
import {
  Music,
  FileText,
  Trash2,
  Check,
  X,
  Play,
  Clock,
  HardDrive,
  RefreshCw,
  Upload,
} from "lucide-react";

interface Track {
  id: string;
  filename: string;
  artist: string;
  title: string;
  duration_seconds: number;
  size_mb: number;
  source_path: string;
  music_prompt: string;
  lyrics: string;
  visual_style: string;
  visual_prompt: string;
  status: string;
  tags: string[];
}

interface TrackManagerProps {
  onSelectTrack?: (track: Track) => void;
}

const STATUS_COLORS: Record<string, string> = {
  pending: "text-gray-400",
  ready: "text-blue-400",
  generating: "text-yellow-400",
  completed: "text-green-400",
  failed: "text-red-400",
};

export function TrackManager({ onSelectTrack }: TrackManagerProps) {
  const [tracks, setTracks] = useState<Track[]>([]);
  const [loading, setLoading] = useState(true);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editField, setEditField] = useState<string | null>(null);
  const [editValue, setEditValue] = useState("");

  const loadTracks = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/data/tracks/");
      if (res.ok) {
        const data = await res.json();
        setTracks(data);
      }
    } catch (err) {
      console.error("Failed to load tracks:", err);
    } finally {
      setLoading(false);
    }
  }, []);

  const importTracks = useCallback(async () => {
    try {
      const res = await fetch("/api/data/tracks/import", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          directory: "E:\\Generated by HappyShrimp(beta)",
        }),
      });
      if (res.ok) {
        loadTracks();
      }
    } catch (err) {
      console.error("Failed to import tracks:", err);
    }
  }, [loadTracks]);

  const importFromCsv = useCallback(async () => {
    try {
      const res = await fetch("/api/data/tracks/import-csv", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });
      if (res.ok) {
        const data = await res.json();
        alert(`Imported ${data.imported} tracks from CSV!`);
        loadTracks();
      }
    } catch (err) {
      console.error("Failed to import from CSV:", err);
    }
  }, [loadTracks]);

  const saveTrack = useCallback(
    async (trackId: string, field: string, value: string) => {
      try {
        await fetch(`/api/data/tracks/${trackId}`, {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ [field]: value }),
        });
        setTracks((prev) =>
          prev.map((t) => (t.id === trackId ? { ...t, [field]: value } : t))
        );
      } catch (err) {
        console.error("Failed to save track:", err);
      }
    },
    []
  );

  const deleteTrack = useCallback(
    async (trackId: string) => {
      try {
        await fetch(`/api/data/tracks/${trackId}`, { method: "DELETE" });
        setTracks((prev) => prev.filter((t) => t.id !== trackId));
      } catch (err) {
        console.error("Failed to delete track:", err);
      }
    },
    []
  );

  const startEditing = (trackId: string, field: string, currentValue: string) => {
    setEditingId(trackId);
    setEditField(field);
    setEditValue(currentValue);
  };

  const saveEdit = () => {
    if (editingId && editField) {
      saveTrack(editingId, editField, editValue);
    }
    setEditingId(null);
    setEditField(null);
    setEditValue("");
  };

  const cancelEdit = () => {
    setEditingId(null);
    setEditField(null);
    setEditValue("");
  };

  useEffect(() => {
    loadTracks();
  }, [loadTracks]);

  const formatDuration = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-8">
        <RefreshCw className="w-6 h-6 animate-spin text-gray-400" />
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-medium text-gray-300">
          Tracks ({tracks.length})
        </h3>
        <div className="flex items-center gap-2">
          <button
            onClick={importFromCsv}
            className="px-3 py-1 bg-green-600/30 border border-green-600/50 text-green-200 rounded text-xs flex items-center gap-1 hover:bg-green-600/50"
          >
            <Upload className="w-3 h-3" />
            Import CSV
          </button>
          <button
            onClick={importTracks}
            className="px-3 py-1 bg-blue-600/30 border border-blue-600/50 text-blue-200 rounded text-xs flex items-center gap-1 hover:bg-blue-600/50"
          >
            <RefreshCw className="w-3 h-3" />
            Import Audio
          </button>
        </div>
      </div>

      {/* Track Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-gray-700 text-gray-400">
              <th className="text-left p-2 w-8">#</th>
              <th className="text-left p-2">Track</th>
              <th className="text-left p-2 w-20">Duration</th>
              <th className="text-left p-2 w-16">Size</th>
              <th className="text-left p-2">Music Prompt</th>
              <th className="text-left p-2">Lyrics</th>
              <th className="text-left p-2 w-24">Visual Style</th>
              <th className="text-left p-2 w-20">Status</th>
              <th className="text-left p-2 w-20">Actions</th>
            </tr>
          </thead>
          <tbody>
            {tracks.map((track, index) => (
              <tr
                key={track.id}
                className="border-b border-gray-800 hover:bg-gray-800/50"
              >
                <td className="p-2 text-gray-500">{index + 1}</td>
                <td className="p-2">
                  <div className="flex items-center gap-2">
                    <Music className="w-3 h-3 text-blue-400 shrink-0" />
                    <div className="min-w-0">
                      <p className="text-gray-200 font-medium truncate">
                        {track.title}
                      </p>
                      <p className="text-gray-500 truncate">{track.artist}</p>
                    </div>
                  </div>
                </td>
                <td className="p-2">
                  <span className="flex items-center gap-1 text-gray-300">
                    <Clock className="w-3 h-3" />
                    {formatDuration(track.duration_seconds)}
                  </span>
                </td>
                <td className="p-2">
                  <span className="flex items-center gap-1 text-gray-300">
                    <HardDrive className="w-3 h-3" />
                    {track.size_mb} MB
                  </span>
                </td>
                <td className="p-2 max-w-48">
                  {editingId === track.id && editField === "music_prompt" ? (
                    <div className="flex items-center gap-1">
                      <textarea
                        value={editValue}
                        onChange={(e) => setEditValue(e.target.value)}
                        className="w-full px-1 py-0.5 bg-gray-900 border border-gray-600 rounded text-xs text-white resize-none"
                        rows={2}
                        autoFocus
                      />
                      <button onClick={saveEdit} className="text-green-400">
                        <Check className="w-3 h-3" />
                      </button>
                      <button onClick={cancelEdit} className="text-red-400">
                        <X className="w-3 h-3" />
                      </button>
                    </div>
                  ) : (
                    <div
                      onClick={() =>
                        startEditing(track.id, "music_prompt", track.music_prompt)
                      }
                      className="cursor-pointer group"
                    >
                      {track.music_prompt ? (
                        <span className="text-gray-300 line-clamp-2">
                          {track.music_prompt}
                        </span>
                      ) : (
                        <span className="text-gray-600 group-hover:text-gray-400">
                          Click to add prompt...
                        </span>
                      )}
                    </div>
                  )}
                </td>
                <td className="p-2 max-w-48">
                  {editingId === track.id && editField === "lyrics" ? (
                    <div className="flex items-start gap-1">
                      <textarea
                        value={editValue}
                        onChange={(e) => setEditValue(e.target.value)}
                        className="w-full px-1 py-0.5 bg-gray-900 border border-gray-600 rounded text-xs text-white resize-none"
                        rows={3}
                        autoFocus
                      />
                      <button onClick={saveEdit} className="text-green-400 mt-0.5">
                        <Check className="w-3 h-3" />
                      </button>
                      <button onClick={cancelEdit} className="text-red-400 mt-0.5">
                        <X className="w-3 h-3" />
                      </button>
                    </div>
                  ) : (
                    <div
                      onClick={() =>
                        startEditing(track.id, "lyrics", track.lyrics)
                      }
                      className="cursor-pointer group"
                    >
                      {track.lyrics ? (
                        <span className="text-gray-300 line-clamp-3 whitespace-pre-line">
                          {track.lyrics.slice(0, 100)}
                          {track.lyrics.length > 100 ? "..." : ""}
                        </span>
                      ) : (
                        <span className="text-gray-600 group-hover:text-gray-400 flex items-center gap-1">
                          <FileText className="w-3 h-3" />
                          Add lyrics...
                        </span>
                      )}
                    </div>
                  )}
                </td>
                <td className="p-2">
                  {editingId === track.id && editField === "visual_style" ? (
                    <div className="flex items-center gap-1">
                      <select
                        value={editValue}
                        onChange={(e) => setEditValue(e.target.value)}
                        className="w-full px-1 py-0.5 bg-gray-900 border border-gray-600 rounded text-xs text-white"
                        autoFocus
                      >
                        <option value="">Select...</option>
                        <option value="cinematic">Cinematic</option>
                        <option value="abstract">Abstract</option>
                        <option value="geometric">Geometric</option>
                        <option value="nature">Nature</option>
                        <option value="glitch">Glitch</option>
                        <option value="minimal">Minimal</option>
                        <option value="surreal">Surreal</option>
                      </select>
                      <button onClick={saveEdit} className="text-green-400">
                        <Check className="w-3 h-3" />
                      </button>
                      <button onClick={cancelEdit} className="text-red-400">
                        <X className="w-3 h-3" />
                      </button>
                    </div>
                  ) : (
                    <div
                      onClick={() =>
                        startEditing(track.id, "visual_style", track.visual_style)
                      }
                      className="cursor-pointer group"
                    >
                      {track.visual_style ? (
                        <span className="text-gray-300">{track.visual_style}</span>
                      ) : (
                        <span className="text-gray-600 group-hover:text-gray-400">
                          Select...
                        </span>
                      )}
                    </div>
                  )}
                </td>
                <td className="p-2">
                  <span className={`text-xs ${STATUS_COLORS[track.status] || "text-gray-400"}`}>
                    {track.status}
                  </span>
                </td>
                <td className="p-2">
                  <div className="flex items-center gap-1">
                    {onSelectTrack && (
                      <button
                        onClick={() => onSelectTrack(track)}
                        className="p-1 text-blue-400 hover:bg-blue-900/30 rounded"
                        title="Use this track"
                      >
                        <Play className="w-3 h-3" />
                      </button>
                    )}
                    <button
                      onClick={() => deleteTrack(track.id)}
                      className="p-1 text-red-400 hover:bg-red-900/30 rounded"
                      title="Delete"
                    >
                      <Trash2 className="w-3 h-3" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {tracks.length === 0 && (
        <div className="text-center py-8 text-gray-500">
          <Music className="w-8 h-8 mx-auto mb-2 opacity-50" />
          <p>No tracks found. Import from HappyShrimp directory to get started.</p>
        </div>
      )}
    </div>
  );
}

export default TrackManager;
