using UnityEngine;
using UnityEditor;
using System.IO;

/// <summary>
/// Editor tool to generate and render the coronation scene.
/// Access via Tools > Coronation > Generate Scene
/// </summary>
public class CoronationEditorTool : EditorWindow
{
    [MenuItem("Tools/Coronation/Generate Scene")]
    static void GenerateScene()
    {
        // Create the scene object
        var sceneObj = new GameObject("CoronationScene");
        var scene = sceneObj.AddComponent<CoronationScene>();
        
        // Set default values
        scene.fps = 24;
        scene.durationSeconds = 10;
        scene.resolutionWidth = 1280;
        scene.resolutionHeight = 720;
        scene.outputPath = "Assets/Textures/render_frames/frame_";
        
        // Create output directory
        Directory.CreateDirectory("Assets/Textures/render_frames");
        
        Debug.Log("Coronation scene generated. Press Play to render frames.");
    }
    
    [MenuItem("Tools/Coronation/Render Frames")]
    static void RenderFrames()
    {
        var scene = FindObjectOfType<CoronationScene>();
        if (scene == null)
        {
            Debug.LogError("No CoronationScene found. Generate scene first.");
            return;
        }
        
        Directory.CreateDirectory("Assets/Textures/render_frames");
        Debug.Log("Rendering will begin in Play Mode. Output: Assets/Textures/render_frames/");
    }
    
    [MenuItem("Tools/Coronation/Create Video")]
    static void CreateVideo()
    {
        string outputPath = "Assets/Textures/render_frames/frame_%04d.png";
        string audioPath = "E:/Generated by HappyShrimp(beta)/NeoCortext - Take the Crown.mp3";
        string videoPath = "output/coronation_final.mp4";
        
        Directory.CreateDirectory("output");
        
        // Use FFmpeg to combine frames + audio
        string ffmpegCmd = $"-y -framerate 24 -i \"{outputPath}\" -i \"{audioPath}\" -c:v libx264 -pix_fmt yuv420p -c:a aac -b:a 192k -shortest \"{videoPath}\"";
        
        Debug.Log($"Run: ffmpeg {ffmpegCmd}");
        Debug.Log("Or use FFmpeg to combine frames manually.");
    }
}
