#!/usr/bin/env python3
"""
Composite rendered frames + audio into the final music video.

Usage:
    python tools/compose_mv.py [--fps 24] [--audio <path>]
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
PROJECT_DIR = TOOLS_DIR.parent
FRAMES_DIR = PROJECT_DIR / "output" / "take-the-crown-mv" / "frames"
OUTPUT_PATH = PROJECT_DIR / "output" / "take-the-crown-mv" / "take-the-crown_15s.mp4"
DEFAULT_AUDIO = r"E:\Generated by HappyShrimp(beta)\NeoCortext - Take the Crown.mp3"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--fps", type=int, default=24)
    parser.add_argument("--audio", default=DEFAULT_AUDIO)
    args = parser.parse_args()

    if not FRAMES_DIR.is_dir():
        raise SystemExit(f"Frames dir not found: {FRAMES_DIR}")

    cmd = [
        "ffmpeg", "-y",
        "-framerate", str(args.fps),
        "-i", str(FRAMES_DIR / "frame_%04d.png"),
        "-i", args.audio,
        "-c:v", "libx264",
        "-preset", "medium",
        "-crf", "18",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac",
        "-b:a", "192k",
        "-shortest",
        "-movflags", "+faststart",
        str(OUTPUT_PATH),
    ]
    print("Running:", " ".join(cmd))
    subprocess.run(cmd, check=True)
    size_mb = OUTPUT_PATH.stat().st_size / (1024 * 1024)
    print(f"Done: {OUTPUT_PATH} ({size_mb:.2f} MB)")


if __name__ == "__main__":
    main()
