"""Generate the real Still I Rise timing contract as a TypeScript module.

Reads output/test-Nathaniel_Smalley___Still_I_Rise-analysis.json (backend
librosa analysis) and emits packages/video-editor/src/lib/stillIRiseTiming.ts.

Usage (studio env):
    D:/conda-envs/nma-studio-cuda/Scripts/python.exe scripts/generate_timing_contract.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_JSON = ROOT / "output" / "test-Nathaniel_Smalley___Still_I_Rise-analysis.json"
OUT_TS = ROOT / "packages" / "video-editor" / "src" / "lib" / "stillIRiseTiming.ts"


def main() -> None:
    d = json.loads(SOURCE_JSON.read_text(encoding="utf-8-sig"))

    duration = float(d["duration_seconds"])
    tempo = float(d["tempo_bpm"])
    conf = float(d.get("confidence", 0.0))
    beats = [float(b) for b in d["beat_times"]]
    sections = d["sections"]
    energy = [float(v) for v in d["energy_curve"]]
    ampl = [float(v) for v in d["amplitude_envelope"]]

    # Beat events: downbeat every 4th beat (4/4 assumption), energy sampled
    # from the amplitude envelope (normalized, slightly boosted).
    beat_lines: list[str] = []
    for i, b in enumerate(beats):
        idx = min(int(b / duration * len(ampl)), len(ampl) - 1) if ampl else 0
        e = min(1.0, ampl[idx] * 1.3) if ampl else 0.6
        down = "true" if i % 4 == 0 else "false"
        beat_lines.append(
            f"    {{ time: {b:.3f}, drumType: null, energy: {e:.3f}, "
            f"isDownbeat: {down}, bpm: {tempo:.1f} }},"
        )

    section_lines: list[str] = []
    for s in sections:
        section_lines.append(
            f'    {{ type: "{s["type"]}", start: {float(s["start"]):.2f}, '
            f'end: {float(s["end"]):.2f}, energy: {float(s.get("energy", 0.6)):.3f}, '
            f"bpm: {tempo:.1f} }},"
        )

    # Energy curve stamped with explicit times (uniform sampling over duration)
    # so interpolateEnergy() binary-searches real time instead of assuming spacing.
    n = len(energy)
    curve_lines: list[str] = []
    for i, v in enumerate(energy):
        t = i * duration / (n - 1)
        curve_lines.append(f"    {{ time: {t:.3f}, value: {v:.4f} }},")

    header = f"""/**
 * Still I Rise — real timing contract generated from
 * output/test-Nathaniel_Smalley___Still_I_Rise-analysis.json
 * (backend librosa analysis, job {d.get("job_id", "unknown")}).
 *
 * Generated by scripts/generate_timing_contract.py — DO NOT hand-edit; regenerate instead.
 *
 * Source stats: {duration:.2f}s, {tempo:.1f} BPM (confidence {conf:.2f}),
 * {len(beats)} beats, {len(sections)} sections, {n} energy points.
 */
import type {{ TimingContract }} from "./timing";

export const STILL_I_RISE_TIMING: TimingContract = {{
  filename: "still-i-rise.mp3",
  duration: {duration:.2f},
  bpm: {tempo:.1f},
  bpmConfidence: {conf:.3f},
  beats: [
"""

    tail = f"""  ],
  sections: [
{chr(10).join(section_lines)}
  ],
  energyCurve: [
{chr(10).join(curve_lines)}
  ],
  amplitudeEnvelope: [{", ".join(f"{v:.4f}" for v in ampl)}],
}};

export const STILL_I_RISE_DURATION_SECONDS = {duration:.2f};
export const STILL_I_RISE_BPM = {tempo:.1f};
"""

    content = header + "\n".join(beat_lines) + "\n" + tail
    OUT_TS.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {OUT_TS} ({len(content.splitlines())} lines, {len(beats)} beats, {len(sections)} sections)")


if __name__ == "__main__":
    main()
