import sys
sys.path.insert(0, r"D:\Backup of Important Data for Windows 11 Upgrade\Native Media AI Studio\packages\backend")

import numpy as np
import librosa
from app.services.cuda import cuda_audio, cuda_available

print(f"CUDA available: {cuda_available()}")

# Load HappyShrimp track
audio_path = r"E:\Generated by HappyShrimp(beta)\NeoCortext - Take the Crown.mp3"
print(f"\nLoading: {audio_path}")

y, sr = librosa.load(audio_path, sr=22050, mono=True)
print(f"Duration: {len(y)/sr:.2f}s, Samples: {len(y)}")

# GPU-accelerated analysis
result = cuda_audio.analyze(y)

# Beat tracking
tempo, beats = librosa.beat.beat_track(y=y, sr=sr, hop_length=cuda_audio.hop_length)
beat_times = librosa.frames_to_time(beats, sr=sr, hop_length=cuda_audio.hop_length).tolist()

print(f"\n=== HappyShrimp Track Analysis ===")
print(f"Computed on: {result['computed_on']}")
print(f"Tempo: {float(tempo[0]):.1f} BPM")
print(f"Beats: {len(beat_times)}")
print(f"First 8 beat times: {[round(t, 2) for t in beat_times[:8]]}")

# Save beat data for Unity
import json
with open(r"D:\Backup of Important Data for Windows 11 Upgrade\Native Media AI Studio\tools\beat_data.json", "w") as f:
    json.dump({"tempo": float(tempo[0]), "beat_times": beat_times, "duration": len(y)/sr}, f)
print(f"\nBeat data saved to tools/beat_data.json")
