"""
Remove ignored test and build caches.

This exists because "delete the ignored stuff" has no safe one-liner on this
machine. `git clean -xdf` is the obvious candidate and the wrong one: at the
repo root it takes `output/`, the generated waveform cache and any other
ignored-but-wanted data with it. Deleting data you only failed to `git add` is
a distinct mistake from deleting data that is regenerable, and this script only
ever does the second.

Deliberate non-goals:

  - It does not touch `output/`. Rendered video and generated audio are ignored
    because they are reproducible, not because they are worthless, and a
    half-finished render is expensive to redo.
  - It does not touch the waveform cache. See the note in AGENTS.md: it is
    untracked and preserved on disk on purpose.
  - It refuses to delete anything git tracks, even if it matches a target name.

Everything it removes is regenerated by the next test run, so this is disk
hygiene rather than a repair. Run it when a gate has finished.

Usage:
  python tools/clean-caches.py --dry-run   # report sizes, delete nothing
  python tools/clean-caches.py             # delete the caches

Exit 0 = done (including "nothing to do"), 1 = a removal failed.
"""
from __future__ import print_function

import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def tracked_files():
    proc = subprocess.Popen(["git", "ls-files"], cwd=ROOT,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, _ = proc.communicate()
    return [p for p in out.decode("utf-8", "replace").split("\n") if p.strip()]


def dir_size(path):
    """Total bytes under a directory."""
    total = 0
    for root, dirs, names in os.walk(path):
        for name in names:
            try:
                total += os.path.getsize(os.path.join(root, name))
            except OSError:
                pass
    return total


def main():
    verbose = "-v" in sys.argv or "--verbose" in sys.argv
    # True means "report only, delete nothing".
    dry_run = "--dry-run" in sys.argv

    # Targets are git-ignored by definition: anything tracked is source, and
    # deleting it is never what a caller of this script means.
    #   .pytest_cache        pytest state; recreating it costs one run
    #   .tsbuildinfo*        TypeScript incremental state
    #   test-results/        Playwright failure artefacts
    #   coverage/ .nyc_output/
    #   playwright-report/   HTML report from the last run
    #   */test-results/      per-workspace copies
    TARGETS = (
        ".pytest_cache",
        ".tsbuildinfo",
        ".tsbuildinfo.tests",
        "test-results",
        "playwright-report",
        "coverage",
        ".nyc_output",
    )
    WORKSPACE_TARGETS = ("packages/frontend/test-results", "packages/video-editor/test-results")

    victims = []
    for rel in TARGETS:
        p = os.path.join(ROOT, rel.replace("/", os.sep))
        if os.path.isdir(p):
            victims.append((rel, dir_size(p)))
        elif os.path.isfile(p):
            victims.append((rel, os.path.getsize(p)))
    for rel in WORKSPACE_TARGETS:
        p = os.path.join(ROOT, rel.replace("/", os.sep))
        if os.path.isdir(p):
            victims.append((rel, dir_size(p)))

    # Anything tracked is off limits, even if it sits under one of these names.
    tracked = set(tracked_files())
    victims = [(r, n) for r, n in victims if r not in tracked]

    if not victims:
        print("nothing to clean (no ignored test/build caches present)")
        return 0

    total = sum(n for _, n in victims)
    print("ignored test/build caches found:")
    for rel, size in sorted(victims, key=lambda x: -x[1]):
        print("  %-40s %8.1f MB" % (rel.replace(os.sep, "/"), size / 1048576.0))
    print("  %-40s %8.1f MB" % ("TOTAL", total / 1048576.0))
    print("")

    if dry_run:
        print("re-run without --dry-run to delete these")
        return 0

    removed = []
    for rel, _ in victims:
        p = os.path.join(ROOT, rel.replace("/", os.sep))
        try:
            if os.path.isdir(p):
                shutil.rmtree(p)
            else:
                os.remove(p)
            removed.append(rel)
        except OSError as e:
            print("  could not remove %s: %s" % (rel, e))

    print("removed %d item(s), freeing %.1f MB"
          % (len(removed), sum(n for r, n in victims if r in removed) / 1048576.0))
    print("note: caches regenerate on the next test run - this is disk hygiene, "
          "not a repair.")
    return 0


if __name__ == "__main__":
    sys.exit(main())