#!/usr/bin/env python3
"""
Composite rendered frames + audio into the final music video.

Usage:
    python tools/compose_mv.py [--fps 24] [--audio <path>]
"""

import argparse
import os
import subprocess

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(TOOLS_DIR)
FRAMES_DIR = os.path.join(PROJECT_DIR, "output", "take-the-crown-mv", "frames")
OUTPUT_PATH = os.path.join(PROJECT_DIR, "output", "take-the-crown-mv",
                           "take-the-crown_15s.mp4")
DEFAULT_AUDIO = r"E:\Generated by HappyShrimp(beta)\NeoCortext - Take the Crown.mp3"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--fps", type=int, default=24)
    parser.add_argument("--audio", default=DEFAULT_AUDIO)
    args = parser.parse_args()

    if not os.path.isdir(FRAMES_DIR):
        raise SystemExit(f"Frames dir not found: {FRAMES_DIR}")

    cmd = [
        "ffmpeg", "-y",
        "-framerate", str(args.fps),
        "-i", os.path.join(FRAMES_DIR, "frame_%04d.png"),
        "-i", args.audio,
        "-c:v", "libx264",
        "-preset", "medium",
        "-crf", "18",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac",
        "-b:a", "192k",
        "-shortest",
        "-movflags", "+faststart",
        OUTPUT_PATH,
    ]
    print("Running:", " ".join(cmd))
    subprocess.run(cmd, check=True)
    size_mb = os.path.getsize(OUTPUT_PATH) / (1024 * 1024)
    print(f"Done: {OUTPUT_PATH} ({size_mb:.2f} MB)")


if __name__ == "__main__":
    main()
